# Introduction

Software is playing an increasingly important role in healthcare. Healthcare providers have been transitioning to electronic patient dossiers and other devices that include or embed software in their daily practice. The combination of big data and Artificial Intelligence (AI) are said to hold great promise for healthcare by allowing for more performant devices to assist medical decision making. While AI is not new to medicine,[^1] the resurgence in the popularity of AI is driven by neural networks that, in combination with hardware advances, have shown high performance on tasks hitherto thought to be beyond the capability of software.[^2]

However, the performance of these models is task dependent and robustness is a known issue of AI.[@hamonRobustnessExplainabilityArtificial2020] There is a big potential for safety and performance issues when these technologies are applied, especially when it affects clinical decision making. Even more so considering the tendency of complex models for overfitting and the difficulty in assessing dataset bias (or data poisoning in its deliberate form) for complex datasets.[@hamonRobustnessExplainabilityArtificial2020] The evolution of software and AI leads to questions of how software is regulated when used in a healthcare scenario as a medical device.

In the EU, medical devices have long been regulated by the Medical Device Directive, but triggered by the PIP-scandal,[@europeancommissionProposalREGULATIONEUROPEAN2012] a new regulatory effort has led to the introduction of the Medical Device Regulation in 2017. According to the EC, this Regulation is going into full effect on the 26th of May 2021.[^3] However, the Directive remains relevant for the coming years given that the last possible date for placing devices on the market under Directive is set for 2024-2025. Even though the Regulation is yet to come into full effect, there are suggestions *that* AI necessitates changes to the regulatory framework,[@minssenWhenDoesStandAlone2020a] although it is unclear *what* these changes are or the specific aspect of AI that need addressing.

To investigate potential shortcomings in the mitigation of the risks posed by AI under the current regulatory framework, we will assess how software, including AI, used for medical purposes, is regulated and what changes the newly introduced EU Medical Device Regulation brings. We assess the legal definition, classification and evidence requirements for medical devices, software and AI. In doing so, answering the following questions: what is software, how does contemporary AI relate to software, when is software (part of) a medical device, how is a medical device that is, or contains, software classified and what are the (evidence) requirements for market approval in the EU of medical devices involving software.
