
# Classification of medical device software {#sec:Classification-of-medical}

In the case that software has a medical purpose and is within the scope of the Directive or Regulation, the next question is how medical device software should be classified. Classification is based on the principle of risk where with a classification into different classes that impose increasingly stringent requirements, among others, on the evidence needed for market approval. The commonalities and differences between the Regulation and the Directive are highlighted to assess whether the former has clarified the regulation of software and medical devices.

## Classification based on risk

Both the Directive and Regulation contain procedures and regulatory requirements that need to ensure that there is sufficient evidence showing that the device is in conformity with regulatory requirements. Whether a device is within the scope of the Directive, or under the scope of the Regulation when the latter comes into effect, the objective remains the same in ensuring that patients have timely access to safe and performant medical devices.^[Preamble 2 @REGULATIONEU2017a] This is equally so for medical devices that involve software, both when considering software as medical device (SaMD),[^7] and software that is embedded a hardware medical device (SiMD).

Both the Directive and Regulation have 4 classes in which medical devices can be classified: class I, IIa, IIb and III.[^8] The classification in these classes is done while: '*taking into account the intended purpose of the devices and their inherent risks*'.^[Art 51(1) @REGULATIONEU2017a] In general, risk is based on the probability of occurrence of harm and the consequences of that harm.[^9] This means that devices are classified higher in accordance with the level of the risk related to its intended purpose. Class I devices are low risk devices, where the manufacturer can declare the conformity with the requirements of the Regulation under its own responsibility and, in general, no notified body is involved.[^10] Recent jurisprudence by the ECJ confirms that the risk related to intended medical purpose is the guiding principle for classification.^[@minssenWhenDoesStandAlone2020a]

Class IIa-III devices require a certificate of conformity issued by a notified body for which the requirements depend on the class and specifics of a device. The requirements per class are further discussed after rules for classifying software are analysed.

A general rule is that when there are multiple devices or modules that together form a device are considered, then the *'strictest rules resulting in the higher classification shall apply*'.^[Annex IX, II, 2.3 @ecCOUNCILDIRECTIVE931993]

## Hardware vs software based classification

In this section we answer the question how software is classified under the Directive and under the Regulation, whether we should distinguish between SiMD and SaMD and if there is any indication that 'AI' is classified any different compared to 'traditional' software. This is done by comparing the Directive to the Regulation, which is where we identify a difference in approach. Where the Directive takes what we call a 'hardware-based' approach, the Regulation takes a 'software-based' approach.

### Medical device directive

As a general rule of classification the Directive states that: '*application of the classification rules shall be governed by the intended purpose of the devices*',[Annex IX, II, 2.1 @ecCOUNCILDIRECTIVE931993] which is the case irrespective of whether it concerns a device consisting of software, hardware or both. Embedded software is classified in accordance with the hardware medical devices it is embedded in.^[Annex IX, II, 2.3 @ecCOUNCILDIRECTIVE931993] However, for classifying stand alone software under the Directive it is important to note that software is an 'active device'. We will first discuss how an active device is defined, after which we will go into the criteria in the Directive that determines the applicability and the classification of software.

#### Active device classification

Stand alone software '*is considered to be an active medical device*',[Annex IX, II, 1.4 @ecCOUNCILDIRECTIVE931993] which entails some additional classification rules, but also means that stand alone software can be classified on its own, without a hardware medical device necessary. Section 3 contains additional rules for active devices. When an active device administers of exchanges energy it is classified as Class IIa or Class IIb depending on the nature, density and site of application of the energy. When an active device controls or monitors the performance of an active therapeutic device of Class IIb, it has the same classification.^[Annex IX, III, 3.1 @ecCOUNCILDIRECTIVE931993] It classifies devices which are intended for diagnostic purposes based on whether they administer, supply or exchange energy, image radiopharmaceuticals *in vivo*, administer or remove medicines, emit ionising radiation or allow direct diagnosis or monitoring of vital physiological processes.^[Annex IX, III, 3.2 @ecCOUNCILDIRECTIVE931993] For stand alone software only the last one is relevant given that the others all require some hardware medical device component on which the classification would be based.

#### Drive a device or influence its use

In addition, it is clear from the Directive that '*Software, which drives a device or influences the use of a device, falls automatically in the same class*'.^[Annex IX, 2.3 @ecCOUNCILDIRECTIVE931993] For SiMD this makes clear how it should be classified, as any embedded software '*drives a device*'. However, it is not immediately evident what this implies for SaMDs, or more standalone software, which communicates with a device. The crux herein is what is meant by '*influences the use of a device*'.

The above indicates that when software '*influences the use of a device*' that it is part of that device could increase the scope of software considered as a medical device if it would be said that software that influences medical decision making and in doing so potentially influencing the physician's decision to use a medical device, would lead to a conflict for software for general purposes used in a healthcare setting, that are explicitly excluded from the scope but evidently do influence medical decision making.^[Preamble 19 @REGULATIONEU2017a]

#### Hardware-based approach

The Directive classifies embedded software, or SiMD, based on the physical medical device. Therefore, the intended medical purpose of the medical device is the relevant factor in classifying these devices and the embedded software. Standalone software is classified as a class I device given that none of the rules lead to a different class when the device has no hardware component.^[Annex IX, 3.3, rule 12 @REGULATIONEU2017a] Given the time frame in which the Directive came into existence, the classification of standalone software in a low class may not come as a big surprise, given that software was less prevalent in a medical context than it is today.

### Medical device regulation

The new medical device Regulation specifically mentions software in its preamble where it clarifies that software confirms to the definition of a medical device that it qualifies as a medical device in its own right. This is a clarification compared to the original Directive, but not a change from the Directive after its 2007 amendment. In this section we assess whether the classification of software, more specifically standalone software, has changed and what the consequences are thereof.

#### Classification

The regulation states that '*the qualification of software, either as a device or an accessory, is independent of the software's location or the type of interconnection between the software and a device*'.^[Preamble 19 @REGULATIONEU2017a] The Regulation, just like the Directive, considers software to be an active device,[Art 2(4) @REGULATIONEU2017a] and states that '*software, which drives a device or influences the use of a device, shall fall within the same class as the device*'.^[Annex VIII, II, 3.3 @REGULATIONEU2017a] The Regulation states that *'if the software is independent of any other device, it shall be classified in its own right*'.^[Annex VIII, II, 3.3 @REGULATIONEU2017a]

The rules for the classification of active devices, which includes software, has many similarities when comparing the Regulation to the Directive. The rule for the classification of active devices controlling other (non-active) devices is similar, [Annex VIII, rule 9 @REGULATIONEU2017a] as is the rule concerning active devices (including software) that supply energy, do *in vivo* imaging of radiopharmaceuticals or exchange of energy, emitting ionising radiation, administer/remove medicines.^[Annex VIII, rule 10 @REGULATIONEU2017a] Another rule concerns active devices that administer or remove medicinal products or similar substances from the body. Although this rule is not very relevant for stand alone software because it cannot perform such physical acts without a hardware component. That would have to be part of that medical devices, as implied by the guidance on rule 12 by the MDCG.[^11] However, there is one new rule in the Regulation that changes the classification of software considerably compared to the Directive.

#### Software-based approach to classification

The Regulation has introduced a new rule 11 that contains an important clarification related to '*software intended to provide information which is used to take decisions with diagnosis or therapeutic purposes*'. This software is classified in class IIa or even higher depending on the seriousness of the impact that the decisions that the devices provide information on.[^12] To clarify the exact meaning of '*to provide information which is used to take decisions with diagnosis or therapeutic purposes*' is, we look at the guidance documents that are available.

According to the Regulation, the European Commission can decide, through implementing acts and after consulting the MDCG, on the application of the classification rules in Annex VIII.^[Art 51(2) @REGULATIONEU2017a] Currently, the Commission has created one implementing act on single use devices. However, the MDCG expert group on new technologies has released a guidance document relevant to the classification rules of software. It should be noted that this guidance is not legally binding.

#### The MDCG on medical device software (MDSW)

The MDCG has the following to say on the software classification rule 11 in the Regulation: '*The wording "intended to provide information which is used to take decisions with diagnosis or therapeutic purposes" describes, in very general terms, the "mode of action" which is characteristic of all MDSW. Therefore, this sub-rule is generally applicable to all MDSW (excluding those MDSW that have no medical purpose)*'.^[@mdcgGuidanceClinicalEvaluation2020 13] The MDCG use the abbreviation 'MDSW' for medical device software, which it defines as follows: '*Medical device software is software that is intended to be used, alone or in combination, for a purpose as specified in the definition of a "medical device" in the medical devices regulation or in vitro diagnostic medical devices regulation'*.^[@mdcgGuidanceClinicalEvaluation2020 6]

While there are products without a medical purpose that are within the scope of the Regulation,[Art 1(2) jo. Annex XVI @REGULATIONEU2017a] meaning that the first sub-rule of rule 11 is not applicable for software used in those devices, the definition of MDSW by the MDCG specifically refers to the definition of a 'medical device', not more generally to products that are within the scope of these Regulations. Because the different purposes specified in the definition of a medical device are all medical purposes, MDSW has a medical purpose by definition.^[Art 2(1) @REGULATIONEU2017a]

As the MDCG has defined MDSW as including both stand alone software and embedded software, what the MDCG is essentially saying is that this part of rule 11 is applicable to all medical devices that have any software. This means that all software is class IIa by default and class IIb or class III if the requirements for one of the two exceptions are met. Evidently this is a very peculiar choice by the MDCG, because the consequence is that software is no longer only classified based on the intended medical purpose and the corresponding risk but based on the choice of implementing the device in hardware or in software. An additional fact that shows the peculiarity of the MDCG's interpretation is that it makes the third sub-rule of rule 11 redundant given that there is no other software to consider when every software is covered by the first sub-rule.

#### An example of the software-based approach

Lets illustrate this by an example. The classification of a relatively simple medical device such a thermometer would differ depending on the implementation. An old mercury thermometer would be a class I device, should the manufacturer use an implementation using electrical components without a computation module such as a microcontroller than it would still be a class I device, but the moment that the sensor is read by such a module and software is used, such a device would be a class IIa device. As there is no reason to assume a higher risk for a software implementation in this case, this shows that the interpretation of the MDCG diverts from the principle that classification is based on the intended medical purpose and associated risk. As such, this interpretation of rule 11 is only really fitting for higher class and thus higher risk software, which currently is the exception.

## Classifying software

In summary, the classification is risk based, where risk consist of the probability of harm occurring and the consequences of the harm done should it occur.

Whereas the Directive takes a '*hardware-based approach*', meaning that it is the hardware medical device that leads to a certain classification. The crux is the line of '*Software, which drives a device or influences the use of a device, falls automatically in the same class'*. In the Directive, a 'true' SaMD, meaning truly standalone software without any connection to a hardware medical device, is classified in class I. The Directive only leaves room for higher classification of software in case there is a hardware medical device that requires this higher class.

The Regulation, in part due to its guidance document, takes a '*software-based approach*'. The relevant classification rule is to classify '*software intended to provide information which is used to take decisions with diagnosis or therapeutic purposes*' through a newly introduced rule 11. This essentially does away with classification of software in relation to the hardware it is embedded in or connected to.[^13] The result is that utilising any form of software under the Regulation, using the guidance by the MDCG, results in a higher classed device regardless of risk.

In conclusion, neither the Directive nor Regulation is fully following its risk-based classification paradigm. In both, the implementation method can dictate classification regardless of the implications it has for the risks related to the device. So far there is no indication of a reason why there is this deviation from that principle in the classification of software specifically. After it is established that software is within the scope of the Directive/Regulation and acknowledging that stand alone software constitutes a medical device, it seems unnecessary to base the classification on whether the implementation is done through software. However there may be implications resulting from the requirements that could explain this approach for software.
