
# Certificates in the Medical Device Regulation {#sec:Certificates-in-the label="sec:Certificates-in-the"}

There are essentially two requirements for every class of device for EU market access: the declaration of conformity and one or more certificates for a device higher than class I. The certificates are issued by a notified body according to article 56, for which Annex XII contains the general requirements and minimum content.^[Annex XII @REGULATIONEU2017a]

::: centering
  Annex    Certificates
  ------- ----------------- ----------------
    IX     QMS (chapter 1)   TD (chapter 2)
     X           TE
    XI      QA = QMS + TD          PV

: Annexes on Conformity Assessment
:::

## Declaration of conformity

The declaration of conformity is drawn up by the manufacturer. A declaration of conformity is a document in which the manufacturer declares that the product complies with the EU requirements and take full responsibility of the product's compliance with the applicable EU law.^[@TechnicalDocumentationEU]

For higher class devices it is part of the assessment done by the notified body where it is, among other things, a basis for a QMS-certificate, QA-certificate and PV-certificate.^[Art 10(6); Annex IX, 2.1 and Annex XI, 5 & 11 @REGULATIONEU2017a] Concretely, the requirement for safety and clinical performance is reflected in the Annex I, 23.4 jo. article 32 of the medical device Regulation where it requires the performance characteristics and the degree of claimed accuracy to be part of the device's documentation.

## EU technical documentation assessment certificate (TD-certificate)

Every product must have a technical documentation as per Annex II (technical documentation) and Annex III (technical documentation on post-market surveillance),[Art 52 @REGULATIONEU2017a] the specific requirements depend on the class of the device.^[Annex IX, 5 @REGULATIONEU2017a] However, an assessment as per Annex IX, chapter II, is only required for class IIb & III medical devices. For these devices the manufacturer lodges an additional application for the assessment of the documentation which describes the design, manufacture and performance of the devices.^[Annex IX, chapter II @REGULATIONEU2017a] The technical documentation can include the claim that the device is equivalent to another device, which the notified body has to verify.^[Annex IX, 4.5 @REGULATIONEU2017a] The notified body also needs to verify that the clinical evidence and the clinical evaluation support the claims of the manufacturer and the conclusions it has drawn from them.^[Annex IX, 4.6 @REGULATIONEU2017a] Based on the clinical evidence, the notified body will consider the benefit-risk determination in the Technical Documentation[Annex II, 5 @REGULATIONEU2017a] and will define specific milestones to update the review of the clinical evidence when more evidence becomes available.^[Annex IX, 4.7 @REGULATIONEU2017a] If all the requirements concerning the technical documentation are fulfilled then the notified body must issue an EU technical documentation assessment certificate.^[Annex IX, 4.10 @REGULATIONEU2017a]

For a TD-certificate, the technical documentation requires information of the intended patient population and medical conditions to be diagnosed, treated and/or monitored by the device.^[Annex II, 1.1(c) @REGULATIONEU2017a] This is especially relevant for AI software where usage outside of the intended population or function can bring robustness issues to light. To support the ability to assess this, the documentation needs to explain the principles of operation,[@hamonRobustnessExplainabilityArtificial2020 24] where the validity and appropriateness of these principles needs to be scientifically demonstrated [Annex II, 1.1(d) @REGULATIONEU2017a] By documenting the general description of key functional elements, which explicitly includes software, it can be assessed whether classification was done properly and whether the necessary element are present to support operations in accordance with the previously mentioned principles of operation.^[Annex II, 1.1(j) @REGULATIONEU2017a] The manufacturer must mention previous and similar devices produced and/or available on the market.^[Annex II, 1.2 @REGULATIONEU2017a] This is relevant as an indication of the risk and available experience with these types of product, but also in the assessment of software modification as will be discussed later.

#### Specific requirements for software

The Technical Documentation must contain detailed information on testing methodology, methods of data analysis and test conclusions regarding software verification and validation. The information for software verification and validation describes '*the software design and development process and evidence of the validation of the software, as used in the finished device.*'[Annex II, 6.1(b), point 3 @REGULATIONEU2017a] Additionally, the Technical Documentation must contain '*information to allow the design stages applied to the device to be understood'*,[Annex II, 3(a) @REGULATIONEU2017a] which is particularly relevant for AI models given that it obligates the manufacturer to show how it designed the model.

Verification and validation are two closely related, but distinct, parts of the quality control process when engineering complex systems.^[@vogelMedicalDeviceSoftware2011 77] Software verification concerns the process of answering the question whether the software conforms to its specification. This is different from software validation, which is answering the question whether the software does what the user wants. The technical documentation *'should typically include the summary results of all verification, validation and testing performed both in-house and in a simulated or actual user environment prior to final release'.*[Annex II, 6.1(b), point 3 @REGULATIONEU2017a] In doing this the manufacturer should consider that its verification and validation procedures *'address all of the different hardware configurations and, where applicable, operating systems identified in the information supplied by the manufacturer)*'.^[Annex II, 6.1(b), point 3 @REGULATIONEU2017a]

Obviously, the validation and verification of complex systems, including software, is difficult. The complexity increases with the number of configurations or variables that need to be considered. More so when the dynamics of a changing model add to the number of variables in a system. The latter is essentially what is so challenging about validating AI. This requires extensive testing, among other things,[@vogelMedicalDeviceSoftware2011 75] to ensure the robustness of the model and further developments in formal verification, a field of computer science which aims to mathematically proof the correctness of software.^[@hamonRobustnessExplainabilityArtificial2020 18-19] While verification is within the context of a training dataset and test dataset is common practice and allows to verify that an AI model performs according to the specification. The generalisability thereof to real world use is not necessarily proven through that method. Consequently, the most challenging part is the validation, which is due to the many variables in a model and the variability of the input data, it is difficult to predict the effect of small changes in the model or input data.

While verification is possible based on the available data,[^17] the results of this verified model may not be robust when applied on new data or cases. The 'validation' of AI models remains an open challenge and one of the reasons why the explainability and interpretability of these models is important as this allows better reasoning on the different aspects of the '*quality*'[^18] of these models.

There is one relevant provision in in Annex III describing the post market surveillance plan for software. This plan should include a process for assessing and acting upon collected data, by using suitable indicators and analysis of statistically significant increase in one or more of the aspects of incidents reported.^[Annex III, 1.1(b) @REGULATIONEU2017a]

#### Additional requirements for class IIb-III devices

There are additional requirements for the technical documentation for class III and some class IIb devices.^[Annex IX, 5 @REGULATIONEU2017a] For these devices the notified body will create a clinical evaluation assessment report for the Commission, which will refer this to the relevant expert panel. The expert panel has the choice to formulate a scientific opinion in which it reviews the report made by the notified body. In this opinion, the expert panel can advice the notified body of required changes.^[Annex IX, 5.1(g) @REGULATIONEU2017a]

## EU quality management system certificate (QMS-certificate)

Article 10 establishes the obligation for manufacturers of any device to establish and implement a quality management system.^[Art 10(9) @REGULATIONEU2017a] For higher class devices the quality management system needs an assessment by a notified body for which the manufacturer has to lodge the application.^[Annex IX, 2.1 @REGULATIONEU2017a] The required documentation primarily concerns the business organisation, the techniques that are used to monitor, verify and control the design of the devices and the corresponding documentation. The notified body will audit the quality management system and corresponding documentation. If it conforms to the relevant provision, the notified body will issue an EU quality management system certificate.^[Annex IX, 2.3 @REGULATIONEU2017a]

While the Regulation requires a surveillance plan for all classes,[Art 83-84 @REGULATIONEU2017a] for medical devices higher than class I, the notified body must perform surveillance and periodic (unannounced) audits of the approved quality management system to ensure that the obligations therein are fulfilled.^[Annex IX, 3 @REGULATIONEU2017a] Related to this is the obligation of manufacturers to create a periodic safety update report (PSUR) for class IIa-III devices.^[Art 86 @REGULATIONEU2017a]

Art 10(9) delineates some specific requirements concerning the quality management system, the regulatory compliance, general safety and performance requirements, responsibility, risk management, information concerning product development and manufacturing, clinical evaluation, verification, post-market surveillance, handling of communications, vigilance, managements of corrective action and monitoring of output in light of data analysis and product improvement.^[Art 10(9) @REGULATIONEU2017a]

Part of the QMS-certificate is the obligation for manufacturers to provide access to technical documentation as referred to in Annexes II and III. Other requirements are that the obligations resulting from the quality management system are fulfilled, that post-market surveillance is conducted and that (documentation of) the clinical evaluation plan is kept up to date. According to Annex IX, the documentation used to asses the quality management system includes the quality objectives,[Annex IX, 2.2(a) @REGULATIONEU2017a] a description of the organisation of business relevant to the design, manufacturing and verification of a product and the procedures and techniques that are used to monitor, verify, validate and control the design of the device.^[Annex IX, 2.2(b-c) @REGULATIONEU2017a] The documentation requires the manufacturer's quality objectives, a description of the organisation and business, procedures and techniques for monitoring, verifying validating and controlling the design of devices. Importantly, it requires a description of the verification and quality assurance techniques including the appropriate tests and trials to be conducted before, during and after manufacturing.^[Annex IX, 2.2 @REGULATIONEU2017a]

There is an obligation for the notified body to audit whether the quality management is compliant with the regulatory requirements.^[Annex IX, 2.3 @REGULATIONEU2017a] For class III & some IIb the QMS certificate has the additional requirement of an assessment of the technical documentation for devices selected on a representative basis in accordance with Annex IX, chapter II.

Evidently, the Regulation requires a quality management system for software to assure regulatory compliance in the the design, manufacturing, validation and verification of that software.[^19] While there is guidance available on for example the software for quality management systems for medical devices,[^20] there are no explicit requirements specifically for the quality management systems concerning software.

## EU Type-examination certificate (TE-certificate) {#subsec:Type-examination label="subsec:Type-examination"}

For an EU type examination the notified body certifies that the device fulfils the relevant provisions in the Regulation. This includes the technical documentation, processes that are relevant during the life cycle of the device and looking at a representative sample of the device produced as envisaged.^[Annex X, 1 @REGULATIONEU2017a] The manufacture needs to lodge an application with a notified body of choice, but needs to declare any other applications it has filed and provide information concerning these applications if applicable.^[Annex X, 2 @REGULATIONEU2017a] The notified body will assess whether the device is in conformity with the requirements of the Regulation and whether the type is manufactured according to the corresponding technical documentation.^[Annex X, 3 @REGULATIONEU2017a] If applicable, the notified body needs to carry out or arrange the appropriate assessments and tests that are necessary to verify that the general safety and performance requirements are met.^[Annex X, 3 (f) @REGULATIONEU2017a] If the type conforms to the regulatory requirements then the notified body will issue a TE-certificate.^[Annex X, 4 @REGULATIONEU2017a]

For some higher class devices that are based on their type have a higher risk, the notified body must submit a clinical evaluation report to the European Commission, which will refer this to the appropriate expert panel for evaluation.^[Art 54(4) jo. annex IX, 5.1 @REGULATIONEU2017a] For certain class IIb-III devices, the manufacturer is given the ability to consult an expert panel,[Art 61(2) @REGULATIONEU2017a] which are part of the MDCG and work under supervision of the European Commission.^[Art 106 @REGULATIONEU2017a] A TE-certificate requires review of the clinical evidence which means clinical data and clinical evaluation results that show the safe and that it achieves its intended clinical benefits.^[Annex X, 3(c) jo. art 2(51) @REGULATIONEU2017a] The manufacturer must assess the evidence in a clinical evaluation, where it assess the conformity of the clinical evidence to the requirements in Annex I.^[Art 61 @REGULATIONEU2017a] While the requirements are applicable to aspects of software development and software products, there are no specific requirements for software concerning a TE-certificate.

## EU quality assurance certificate (QA-certificate)

The QA-certificate is a step up from the QMS-certificate as it requires that the approved quality management system is implemented and verified. As such, a QA-certificate requires essentially all of the elements that are required for a QMS-certificate,[Annex XI, 6 @REGULATIONEU2017a] except for 2.2(c) which concerns the procedures and techniques for verification and is thus covered by the requirements for QA-certificate instead.^[Annex XI, 6.2 jo. Annex IX, 2.2(d) @REGULATIONEU2017a] One of the requirements is that the application for a QA-certificate includes the technical documentation as required by Annexes II & III.^[Annex XI, 6.1 @REGULATIONEU2017a] The certificate is issued when the quality management system ensures that the devices described in the TE-certificate conform to the requirements in the regulation. To assert that the requirements are met, notified bodies carry out surveillance, including (un)announced onsite audits and the assessment of information in the quality management system, documentation, data related to the design, tests and records of the qualifications of personnel and quality control reports.^[Annex IX, 3 @REGULATIONEU2017a]

While the quality assurance certificate has no specific requirements for software, given the importance of quality assurance of software, it is very relevant for the quality management system and general requirements of Annex I as relevant for software.

## Product verification certificate (PV-certificate)

The objective a product conformity verification has is to assess that a device conforms to the type for which an EU type-examination certificate has been issued (see [subsec:Type-examination](#subsec:Type-examination){reference-type="ref" reference="subsec:Type-examination"}) This is an extra check on the work done by the notified body in issuing the EU type-examination. Other than the QA-certificate, a PV-certificate concerns each individual product contrary to the production process.^[Annex XI, 15 @REGULATIONEU2017a] As such, it is not that relevant for software, where the verification is done on the 'design' of the software. The product verification of every device is an easy requirement to meet for software given that copying software is highly reliable and can be easily checked through a checksum that guarantees that the 'software' is copied as intended.

Therefore, the PV-certificate has no specific requirements for software. The product verification for a PV-certificate essentially concerns the hardware aspects of the device, but is not that relevant for software.

## Certificate of free sale

The certificate of free sale is a certificate that is issued by the Member States in which the manufacturer or authorised representative has its registered place of business for a device that is in accordance with the Regulation.^[Art 60 @REGULATIONEU2017a] As its name implies this certificate allows the free sale of a device with the European Economic Area (EEA).[^21] A free sales certificate requires that the device bears a CE marking and that the manufacturer or authorise representative has its registered place of business in a Member State.^[Art 60 @REGULATIONEU2017a] It contains the UDI-DI and the identification number of the certificate of conformity.^[Art 60 @REGULATIONEU2017a]
